# Generated by Django 4.2.10 on 2024-04-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_writer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
