# Generated by Django 4.2.10 on 2024-04-16 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_writer_username'),
    ]

    operations = [
    ]
