# Generated by Django 4.2.10 on 2024-04-16 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20240416_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editor',
            name='slug',
        ),
    ]
