# Generated by Django 4.2.10 on 2024-04-16 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_remove_editor_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writer',
            name='slug',
        ),
    ]
