# Generated by Django 4.2.10 on 2024-04-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_writer_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='editor',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
