# Generated by Django 4.2.10 on 2024-04-22 15:42

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_editor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='writer',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='username', unique=True),
        ),
    ]
