# Generated by Django 4.2.10 on 2024-04-27 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0010_alter_editor_slug_alter_writer_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Editor',
        ),
        migrations.AddField(
            model_name='writer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
