# Generated by Django 4.2.10 on 2024-04-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_delete_editor_writer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writer',
            name='id',
        ),
        migrations.AlterField(
            model_name='writer',
            name='username',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
