# Generated by Django 4.2.10 on 2024-04-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_remove_writer_id_alter_writer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
