# Generated by Django 4.2.10 on 2024-05-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_alter_writer_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='photo',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
    ]
