# Generated by Django 4.2.10 on 2024-05-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_alter_writer_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writer',
            name='resume',
        ),
        migrations.AddField(
            model_name='writer',
            name='facebook_link',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='writer',
            name='instagram_link',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='writer',
            name='linkedin_link',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='writer',
            name='photo',
            field=models.ImageField(blank=True, default='example.jpg', upload_to=''),
        ),
    ]
