# Generated by Django 4.2.10 on 2024-05-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_remove_writer_resume_writer_facebook_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='writer',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='writer',
            name='linkedin_link',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
