# Generated by Django 4.2.10 on 2024-05-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_writer_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='about_me',
            field=models.TextField(blank=True),
        ),
    ]
