# Generated by Django 4.2.10 on 2024-05-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_alter_writer_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='goal',
            field=models.CharField(choices=[('Writer', 'Writer'), ('Editor', 'Editor')], default='Writer', max_length=9),
        ),
    ]
