# Generated by Django 4.2.10 on 2024-05-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_alter_writer_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='phone',
            field=models.IntegerField(blank=True, default=0, max_length=12),
            preserve_default=False,
        ),
    ]
