# Generated by Django 4.2.10 on 2024-05-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_writer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='phone',
            field=models.CharField(blank=True, max_length=12)
        ),
    ]
