# Generated by Django 4.2.10 on 2024-05-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_alter_writer_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='goal',
            field=models.CharField(default='Writer'),
        ),
    ]
