# Generated by Django 4.2.10 on 2024-05-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0025_alter_writer_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='vis',
            field=models.CharField(choices=[('Visible', 'Visible'), ('Hidden', 'Hidden')], default='Visible', max_length=9),
        ),
        migrations.AlterField(
            model_name='writer',
            name='goal',
            field=models.CharField(choices=[('Writer', 'Writer'), ('Editor', 'Editor')], default='Editor', max_length=9),
        ),
    ]
