# Generated by Django 4.2.10 on 2024-05-13 22:58

import cloudinary.models
from django.db import migrations
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0029_alter_writer_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, validators=[profiles.models.validate_image_size], verbose_name='image'),
        ),
    ]
