# Generated by Django 4.2.10 on 2024-04-03 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Xyz',
            new_name='Stories',
        ),
    ]
