# Generated by Django 4.2.10 on 2024-04-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_remove_story_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='story',
            field=models.TextField(default=''),
        ),
    ]
