# Generated by Django 4.2.10 on 2024-04-16 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_story_story'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='story',
        ),
    ]
