# Generated by Django 4.2.10 on 2024-04-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0008_remove_story_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='keywords',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='story',
            name='story_text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='story',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='story',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
