# Generated by Django 4.2.10 on 2024-04-19 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_editor_slug'),
        ('stories', '0009_story_keywords_story_story_text_alter_story_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.writer'),
        ),
    ]
