# Generated by Django 4.2.10 on 2024-04-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0014_alter_story_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commented_story',
            new_name='story',
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
