# Generated by Django 4.2.10 on 2024-05-04 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0017_rename_story_comment_commented_story'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
    ]
