# Generated by Django 4.2.10 on 2024-05-09 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0020_story_likes_delete_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='image',
        ),
    ]
